### ISSUE TITLE
organising challenges in a single repo

### ISSUE THREAD

**Issue by kabir-afk** [KrishnaVishwakarma1595/frontend-mentor#1]
hey ✋  I just wanted to know how are you maintaining your challenges inside a single repo while still being able to deploy each challenge individually on pages...I wanted to achieve the same so that my github looks more organized , since I'll be loading codes besides frontend mentor challenge as well, btw commendable work , your codes are super easy to read despite having little knowledge and your sites are pixel perfect...keep up the good work , wish to code like you someday brdr 😭

**Comment by KrishnaVishwakarma1595** [comment]
Hi, @kabir-afk, Thanks for this warm appreciation. I'm so grateful. 😊😇

For the repository organising, I didn't do much. I have a root index.html file that serves as the base/home page of my projects and for the challenges, I just created the challenge-level base sub-directories and pushed them respectively. So, I can access every challenge by absolute path.

As you can see, previously I also had different repos for each challenge but then I felt it would be very difficult to maintain them or I would have a large bunch of repos for the challenge, so I just created a single one and maintained everything into one place. So anyone who will come up to my repo can easily find my solutions in one place. 🤩

You can do the same if you want. It just depends on how we are going to maintain or what we want from the repo.

Hope you understand 😊, Feel free to reach out to me anytime. Also if you want you can follow me here I post my solutions there too and some other tips & tricks regarding the front-end technologies. 

Follow me on LinkedIn - [Krishna Vishwawakarma](https://www.linkedin.com/in/krishna-vishwakarma-139579128/)
Follow me on my Instagram Page - [creative_ui_design](https://www.instagram.com/creative__ui_design/?hl=en)

Keep Developing 🤩

**Comment by kabir-afk** [comment]
well I had trouble creating "level base sub-directories" 😅  so I was wondering if you could provide me with a source or step-by-step guide on how to achieve the same ,glad you replied , I'll follow you on LinkedIn as soon as I come

**Comment by KrishnaVishwakarma1595** [comment]
Well, I didn't use any source or guide for this. You can do the same as I did, just keep the index.html file at the root and while deploying to GitHub pages(if you are using) select the '/root' instead of any other directory.

**Comment by kabir-afk** [comment]
😮 😮  . . . ok i'll try it out, thanks again
